// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hvvzsogcfnoxmwhykypo.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imh2dnpzb2djZm5veG13aHlreXBvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQyODMyNDksImV4cCI6MjA1OTg1OTI0OX0.kBcTdP9iep3zsNP8-mgoapKtvpy5N4pnPh0qraB5rkU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);